import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import prefect.runtime.flow_run
import prefect.runtime.task_run
from prefect.artifacts import acreate_markdown_artifact
from prefect.utilities.asyncutils import run_coro_as_sync

from hpc_relay._sbatch import (
    SlurmJobResult,
    _artifact_key_part,
    _format_output_section,
    wait_completion_single,
)
from hpc_relay.cmd_runners import (
    CmdContext,
    Command,
    get_command_runner,
    run_cmd,
)
from hpc_relay.prefect import get_run_logger, task
from hpc_relay.result import OpError, Result, is_err
from hpc_relay.run import get_head_tail_logs
from hpc_relay.slurm import SlurmJobId, SlurmSubmissionResult

_logger = logging.getLogger(__name__)

__all__ = ["launch_slurm", "LaunchSlurm", "wait_for_completion"]


@dataclass
class LaunchSlurm:
    """
    All the tracking information when using the launch-slurm
    command.
    """

    # The run_id generated by the weathergenerator launch-slurm command.
    wg_run_id: str

    # The name of the stage (e.g. "train")
    stage: str

    # The main jobs:
    # The stdout stderr paths are reconstructed from wg_work_dir:
    slurm_jobs: list[SlurmSubmissionResult]
    # Cleanup job: TODO, it is hard to get from summary right now
    # cleanup_slurm_job: SlurmSubmissionResult | None
    # A path to the working dir in weathergenerator (called slurm_... typically)
    wg_work_dir: str

    # The path to the main output logs from the python job.
    # They are of the form:
    # "{wg_work_dir}/WeatherGenerator/logs/{wg_run_id}/output.{job_id}.txt"
    output_logs: dict[SlurmJobId, str]


# Matches the per-stage summary lines printed by launch_slurm.py, e.g.:
#   [train     ] 'train' | run_id=c9ika5od | job_ids=[921904] |
#       start_after=immediately | dir=/iopsstor/.../slurm_weathergen_c9ika5od_dir
_SUMMARY_LINE_RE = re.compile(
    r"run_id=(?P<run_id>\S+)\s*\|"
    r"\s*job_ids=\[(?P<job_ids>[^\]]*)\]\s*\|"
    r".*?dir=(?P<dir>\S+)"
)


# Truncation limits for command output embedded in markdown artifacts, per
# side (head/tail). Same values as get_head_tail_logs in run.py.
_MAX_OUTPUT_BYTES = 100_000
_MAX_OUTPUT_LINES = 100


def _head_tail(text: str) -> str:
    """Truncate `text` to its head and tail (by lines and bytes) for artifacts.

    Returns the text unchanged when it fits within a single head window;
    otherwise returns head + elision marker + tail.
    """

    def _clip(s: str) -> str:
        return s.encode()[:_MAX_OUTPUT_BYTES].decode(errors="ignore")

    lines = text.splitlines()
    if len(lines) <= _MAX_OUTPUT_LINES and len(text.encode()) <= _MAX_OUTPUT_BYTES:
        return text
    head = _clip("\n".join(lines[:_MAX_OUTPUT_LINES]))
    tail = _clip("\n".join(lines[-_MAX_OUTPUT_LINES:]))
    return f"{head}\n[... truncated ...]\n{tail}"


def _output_md_section(title: str, body: str | None) -> str:
    """A markdown section with head/tail-truncated command output.

    Uses 4-backtick fences so content containing ``` doesn't break the block.
    """
    if body is None:
        return f"### {title}\n\n_(not available)_\n\n"
    if body == "":
        return f"### {title}\n\n_(empty)_\n\n"
    return f"### {title}\n\n````\n{_head_tail(body)}\n````\n\n"


async def _publish_launch_error_artifact(
    logger: logging.Logger,
    stage: str,
    from_run_id: str | None,
    error: str,
    stdout: str | None,
    stderr: str | None,
) -> None:
    """Publish a markdown artifact for a failed launch-slurm.py invocation.

    On failure there is no wg run_id to key the artifact on (the key of the
    success artifact relies on parsing the output, which is exactly what
    failed), so key on the task run id instead: it is unique per attempt,
    so retries do not supersede each other's diagnostics.

    Best effort: a failure to publish must not mask the original error.
    """
    short = (prefect.runtime.task_run.id or prefect.runtime.flow_run.id or "")[:8] or "local"
    key = f"wg-launch-error-{_artifact_key_part(stage)}-{_artifact_key_part(short)}"
    md = (
        f"## WeatherGenerator launch-slurm FAILED\n\n"
        f"- **Stage:** `{stage}`\n"
        f"- **From run ID:** `{from_run_id}`\n"
        f"- **Error:** {error}\n\n"
        + _output_md_section("launch-slurm.py stdout", stdout)
        + _output_md_section("launch-slurm.py stderr", stderr)
    )
    try:
        await acreate_markdown_artifact(
            key=key,
            markdown=md,
            description=f"wg launch failure, stage {stage}",
        )
    except Exception as e:
        logger.warning(f"Could not publish the launch error artifact {key}: {e}")


def _parse_launch_summary(output: str) -> tuple[str, list[SlurmJobId], str] | None:
    """
    Extract (run_id, job_ids, work_dir) from the launch_slurm.py summary block.

    There is one summary line per stage; each line may carry several job ids.
    All lines are expected to share the same run_id and work dir. Returns None
    if no summary line is found, raises ValueError on inconsistent lines.
    """
    run_id: str | None = None
    work_dir: str | None = None
    job_ids: list[SlurmJobId] = []

    for match in _SUMMARY_LINE_RE.finditer(output):
        line_run_id = match.group("run_id")
        line_dir = match.group("dir")
        if run_id is None:
            run_id, work_dir = line_run_id, line_dir
        elif (line_run_id, line_dir) != (run_id, work_dir):
            raise ValueError(
                "Inconsistent summary lines from launch_slurm.py: "
                f"expected run_id={run_id} dir={work_dir}, "
                f"got run_id={line_run_id} dir={line_dir}"
            )
        for token in match.group("job_ids").split(","):
            token = token.strip()
            if token:
                job_ids.append(token)

    if run_id is None or work_dir is None:
        return None
    if not job_ids:
        raise ValueError(f"Summary lines for run_id={run_id} contain no job ids")
    return run_id, job_ids, work_dir


@dataclass(frozen=True)
class _LaunchSlurmOptions:
    """Options for the WeatherGenerator launch-slurm command."""

    # Can be relative or absolute from the working dir.
    # If working_dir is specified, the wg_private_path can be relative from this path.
    wg_private_path: str
    # --stage: train, inference, or evaluation. Ignored when `pipeline` is set.
    stage: Literal["train", "inference", "evaluation"] = "train"
    # --from-run-id: run id to continue (training) or trained model to use
    # (inference, required there).
    from_run_id: str | None = None
    # The working directory. All the config paths will be relative to this directory.
    # By default, it is wg_private_path.
    working_dir: str | None = None
    # --slurm-script: path to the slurm script (must be in
    # WeatherGenerator-private/hpc/).
    slurm_script: str | None = None
    # --results-dir: "shared" (script default), "local", or a directory path.
    results_dir: str | None = None
    # --run-ids: inference run ids to evaluate (evaluation stage only;
    # required in single-stage evaluation mode).
    run_ids: list[str] | None = None
    # --dir: root directory for slurm job artifacts and copies.
    root_dir: str | None = None
    # --link-venv: link the current venv instead of creating a fresh one.
    link_venv: bool = False
    # --config: experiment-specific config files, ascending precedence.
    config: list[str] | None = None
    # --options: individual config overrides (parent_obj.nested_obj=value);
    # takes precedence over --config.
    options: list[str] | None = None
    # --base-config: base config for fresh training (script defaults to
    # ./config/default_config.yml).
    base_config: str | None = None
    # --eval-config: evaluation yaml config passed to run_evaluation.py
    # (evaluation stage only).
    eval_config: str | None = None
    # --mini-epoch: mini-epoch for continuing training / loading a model for
    # inference (script default -1 = latest checkpoint).
    mini_epoch: int | None = None
    # --register / --no-register: None keeps the script default (register),
    # True forces --register, False passes --no-register.
    register: bool | None = None
    # --cleanup-scripts: "yes" (script default) or "no".
    cleanup_scripts: Literal["yes", "no"] | None = None
    # --nodes: number of nodes (1-8); ignored for evaluation (always 1).
    nodes: int | None = None
    # --chain-jobs: consecutive training jobs to chain (training only).
    chain_jobs: Literal[1, 2, 3, 4] | None = None
    # --account: slurm account; falls back to BUDGET_ACCOUNTS env var.
    account: str | None = None
    # --nsys-profiling: enables nsys profiling in the job environment.
    nsys_profiling: bool = False
    # --time: walltime limit for the slurm jobs.
    time: str | None = None


@task
def launch_slurm(
    ctx: CmdContext,
    wg_private_path: str,
    stage: Literal["train", "inference", "evaluation"] = "train",
    from_run_id: str | None = None,
    working_dir: str | None = None,
    *,
    slurm_script: str | None = None,
    results_dir: str | None = None,
    run_ids: list[str] | None = None,
    root_dir: str | None = None,
    link_venv: bool = False,
    config: list[str] | None = None,
    options: list[str] | None = None,
    base_config: str | None = None,
    eval_config: str | None = None,
    mini_epoch: int | None = None,
    register: bool | None = None,
    cleanup_scripts: Literal["yes", "no"] | None = None,
    nodes: int | None = None,
    chain_jobs: Literal[1, 2, 3, 4] | None = None,
    account: str | None = None,
    nsys_profiling: bool = False,
    time: str | None = None,
) -> Result[LaunchSlurm]:
    """Blocking task facade for `launch-slurm.py`; async work stays in the helper below."""
    launch = _LaunchSlurmOptions(
        wg_private_path=wg_private_path,
        stage=stage,
        from_run_id=from_run_id,
        working_dir=working_dir,
        slurm_script=slurm_script,
        results_dir=results_dir,
        run_ids=run_ids,
        root_dir=root_dir,
        link_venv=link_venv,
        config=config,
        options=options,
        base_config=base_config,
        eval_config=eval_config,
        mini_epoch=mini_epoch,
        register=register,
        cleanup_scripts=cleanup_scripts,
        nodes=nodes,
        chain_jobs=chain_jobs,
        account=account,
        nsys_profiling=nsys_profiling,
        time=time,
    )
    logger = get_run_logger()
    return run_coro_as_sync(_launch_slurm_async(logger, ctx, launch))


async def _launch_slurm_async(
    logger: logging.Logger,
    ctx: CmdContext,
    launch: _LaunchSlurmOptions,
) -> Result[LaunchSlurm]:
    """
    Launch a sequence of slurm jobs using the weathergenerator
    launch_slurm.py command, and returns the terminal results
    with status of all the launch_slurm jobs.

    Each keyword argument maps to the launch-slurm.py CLI flag named in the
    comment above it; None (or False for flags) means "do not pass the flag"
    so the script's own default applies.

    If `working_dir` is set, the command runs from that directory on the HPC
    (the runners materialize it as a `cd` before the command), so
    `wg_private_path` and the config paths may be relative to it. Otherwise
    the command runs from `wg_private_path` itself.
    """
    # Do not attempt to run expanduser() or resolve(), it runs on the remote HPC
    # and python will not have the appropriate file system information.
    if launch.working_dir is not None:
        # The command runs from working_dir: wg_private_path may be relative to it.
        cwd = launch.working_dir
        script = str(Path(launch.wg_private_path) / "hpc" / "launch-slurm.py")
    else:
        # Default: run from wg_private_path itself, with the script path
        # relative to it (avoids double-prefixing when wg_private_path is
        # itself relative, e.g. to the remote home).
        cwd = launch.wg_private_path
        script = "hpc/launch-slurm.py"
    cmd = [script, "--stage", launch.stage]
    if launch.from_run_id:
        cmd += ["--from-run-id", launch.from_run_id]
    if launch.slurm_script:
        cmd += ["--slurm-script", launch.slurm_script]
    if launch.results_dir:
        cmd += ["--results-dir", launch.results_dir]
    if launch.run_ids:
        cmd += ["--run-ids", *launch.run_ids]
    if launch.root_dir:
        cmd += ["--dir", launch.root_dir]
    if launch.link_venv:
        cmd += ["--link-venv"]
    if launch.config:
        cmd += ["--config", *launch.config]
    if launch.options:
        cmd += ["--options", *launch.options]
    if launch.base_config:
        cmd += ["--base-config", launch.base_config]
    if launch.eval_config:
        cmd += ["--eval-config", launch.eval_config]
    if launch.mini_epoch is not None:
        cmd += ["--mini-epoch", str(launch.mini_epoch)]
    if launch.register is not None:
        cmd += ["--register" if launch.register else "--no-register"]
    if launch.cleanup_scripts:
        cmd += ["--cleanup-scripts", launch.cleanup_scripts]
    if launch.nodes is not None:
        cmd += ["--nodes", str(launch.nodes)]
    if launch.chain_jobs is not None:
        cmd += ["--chain-jobs", str(launch.chain_jobs)]
    if launch.account:
        cmd += ["--account", launch.account]
    if launch.nsys_profiling:
        cmd += ["--nsys-profiling"]
    if launch.time:
        cmd += ["--time", launch.time]
    res = await run_cmd(ctx, Command(cmd, working_directory=cwd), logger)
    if is_err(res):
        await _publish_launch_error_artifact(
            logger,
            launch.stage,
            launch.from_run_id,
            f"command failed: {res.err}",
            res.stdout,
            res.stderr,
        )
        return res
    if res.return_code != 0:
        await _publish_launch_error_artifact(
            logger,
            launch.stage,
            launch.from_run_id,
            f"launch_slurm.py exited with return code {res.return_code}",
            res.stdout,
            res.stderr,
        )
        return OpError(
            err=RuntimeError(f"launch_slurm.py exited with return code {res.return_code}"),
            stdout=res.stdout,
            stderr=res.stderr,
            return_code=res.return_code,
        )

    # Logging may end up on stdout or stderr depending on the handler config,
    # so look in both.
    try:
        parsed = _parse_launch_summary(res.stdout) or _parse_launch_summary(res.stderr)
    except ValueError as e:
        await _publish_launch_error_artifact(
            logger,
            launch.stage,
            launch.from_run_id,
            f"malformed summary block: {e}",
            res.stdout,
            res.stderr,
        )
        return OpError(err=e, stdout=res.stdout, stderr=res.stderr, return_code=res.return_code)
    if parsed is None:
        await _publish_launch_error_artifact(
            logger,
            launch.stage,
            launch.from_run_id,
            "could not find a summary block in launch_slurm.py output",
            res.stdout,
            res.stderr,
        )
        return OpError(
            err=ValueError("Could not find a summary block in launch_slurm.py output"),
            stdout=res.stdout,
            stderr=res.stderr,
            return_code=res.return_code,
        )
    run_id, slurm_job_ids, wg_work_dir = parsed

    # From that, all the log paths can be reconstructed:
    # {wg_work_dir}/WeatherGenerator/logs/{run_id}/weathergen.part{n+1}.{job_id}.{out,err}
    logs_dir = Path(wg_work_dir) / "WeatherGenerator" / "logs" / run_id
    slurm_jobs = [
        SlurmSubmissionResult(
            job_id=job_id,
            stdout=logs_dir / f"weathergen.part{n + 1}.{job_id}.out",
            stderr=logs_dir / f"weathergen.part{n + 1}.{job_id}.err",
        )
        for n, job_id in enumerate(slurm_job_ids)
    ]
    # The main output logs of the python job itself:
    # {wg_work_dir}/WeatherGenerator/logs/{run_id}/output.{job_id}.txt
    output_logs = {job_id: str(logs_dir / f"output.{job_id}.txt") for job_id in slurm_job_ids}

    # Surface the launch details in the Prefect UI as a markdown artifact:
    # all the info in LaunchSlurm plus the launch command's stdout/stderr.
    jobs_md = "\n".join(
        f"| {n + 1} | `{sub.job_id}` | `{sub.stdout}` | `{sub.stderr}` "
        f"| `{output_logs[sub.job_id]}` |"
        for n, sub in enumerate(slurm_jobs)
    )
    launch_md = (
        f"## WeatherGenerator launch-slurm\n\n"
        f"- **Run ID:** `{run_id}`\n"
        f"- **Stage:** `{launch.stage}`\n"
        f"- **From run ID:** `{launch.from_run_id}`\n"
        f"- **Work dir:** `{wg_work_dir}`\n\n"
        f"### Jobs\n\n"
        f"| part | job id | stdout | stderr | output log |\n"
        f"| --- | --- | --- | --- | --- |\n"
        f"{jobs_md}\n\n"
        + _output_md_section("launch-slurm.py stdout", res.stdout)
        + _output_md_section("launch-slurm.py stderr", res.stderr)
    )
    await acreate_markdown_artifact(
        key=f"wg-{_artifact_key_part(run_id)}-launch",
        markdown=launch_md,
        description=f"wg run {run_id} stage {launch.stage} launch",
    )

    return LaunchSlurm(
        wg_run_id=run_id,
        stage=launch.stage,
        slurm_jobs=slurm_jobs,
        wg_work_dir=wg_work_dir,
        output_logs=output_logs,
    )


@task
def wait_for_completion(
    ctx: CmdContext, ls: LaunchSlurm, fetch_output: bool = True
) -> Result[list[SlurmJobResult]]:
    """
    Wait until all the slurm jobs launched by `launch_slurm` reach a terminal
    state, and return their final results (in the same order as `ls.slurm_jobs`).

    The jobs are awaited one after the other: slurm executes them sequentially
    (each part starts after the previous one), so waiting on them in order does
    not add latency.
    """
    logger = get_run_logger()
    _runner = get_command_runner(ctx)
    if isinstance(_runner, Exception):
        return OpError(err=_runner)

    results: list[SlurmJobResult] = []
    for n, sub in enumerate(ls.slurm_jobs):
        logger.info(
            f"Waiting for slurm job {sub.job_id} (run_id={ls.wg_run_id}) on hpc {_runner.hpc}"
        )
        state = run_coro_as_sync(wait_completion_single(logger, ctx, sub.job_id, _runner))
        if is_err(state):
            return state
        logger.info(f"Slurm job {sub.job_id} (run_id={ls.wg_run_id}) finished: {state}")

        # Publish the job details (and optionally its captured logs) in the
        # Prefect UI as a markdown artifact, one per part.
        artifact_key = (
            f"wg-{_artifact_key_part(ls.wg_run_id)}-{_artifact_key_part(ls.stage)}-part{n + 1}"
        )
        output_log = ls.output_logs.get(sub.job_id)
        job_md = (
            f"## WeatherGenerator slurm job\n\n"
            f"- **Run ID:** `{ls.wg_run_id}`\n"
            f"- **Stage:** `{ls.stage}` (part {n + 1}/{len(ls.slurm_jobs)})\n"
            f"- **Job ID:** `{sub.job_id}`\n"
            f"- **HPC:** `{_runner.hpc}`\n"
            f"- **Status:** `{state}`\n"
            f"- **stdout:** `{sub.stdout}`\n"
            f"- **stderr:** `{sub.stderr}`\n"
            f"- **output log:** `{output_log}`\n"
        )
        if fetch_output:
            # Fetch head and tail of stdout and stderr for debugging purposes.
            output = get_head_tail_logs(
                ctx=ctx,
                stdout_path=str(sub.stdout),
                stderr_path=str(sub.stderr) if sub.stderr else None,
            )
            logger.info(
                f"Fetched head/tail logs for job {sub.job_id} on hpc {_runner.hpc}: {output}"
            )
            job_md += "\n" + _format_output_section(output)
            if output_log:
                # The main output log of the python job itself. Fetched
                # separately: get_head_tail_logs reads one stdout/stderr pair.
                py_output = get_head_tail_logs(ctx=ctx, stdout_path=output_log, stderr_path=None)
                job_md += "\n" + (
                    "## Python job output log\n\n"
                    + _output_md_section("output log (head)", py_output.get("head_out"))
                    + _output_md_section("output log (tail)", py_output.get("tail_out"))
                )
        run_coro_as_sync(
            acreate_markdown_artifact(
                key=artifact_key,
                markdown=job_md,
                description=f"wg run {ls.wg_run_id} stage {ls.stage} part {n + 1}",
            )
        )

        results.append(SlurmJobResult(job_id=sub.job_id, status=state, submission=sub))
    return results
